name: financial_py_date
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python>=3.11
  - numpy>=1.26.4
  - numba>=0.59.1
  - pytest=8.3.3
  - mypy=1.13
  - ruff=0.8.1
  - pre-commit=4.0.1
  - pip:
      - QuantLib==1.36