name: financial_py_date
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0.1
  - python>=3.12
  - numpy>=1.26.4
  - numba>=0.61.0
  - pytest=8.3.5
  - mypy=1.15
  - ruff=0.11.2
  - pre-commit=4.2.0
  - pip:
      - QuantLib==1.37